name: Setup and Test (PR)

on:
  pull_request:
    branches: [develop, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup project
        uses: ./.github/actions/setup-project

      - name: Run tests
        uses: ./.github/actions/run-tests
