name: Master Push

on:
  push:
    branches: [develop, master]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
      SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      STAGING_URL: cicdreactstage.surge.sh
      PRODUCTION_URL: cicdreact.surge.sh

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup project and run tests
        uses: ./.github/actions/setup-project

      - name: Build and deploy to production
        if: ${{ github.ref_name }} == develop
        uses: ./.github/actions/build-and-deploy
        with:
          deploy_url: ${{ env.STAGING_URL }}

      - name: Build and deploy to production
        if: ${{ github.ref_name }} == master
        uses: ./.github/actions/build-and-deploy
        with:
          deploy_url: ${{ env.PRODUCTION_URL }}
